#
# This file is part of Python Client Library for SampleDB.
# Copyright (C) 2019 INPE.
#
# Python Client Library for SampleDB is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

sudo: false

language: python

cache:
    directories:
        - $HOME/.cache/pip

branches:
    only:
        - master

dist: bionic

python:
    - "3.7"

before_install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade wheel

install:
    - pip install -e .[tests,docs]

script:
    - ./run-tests.sh

after_success:
    - coveralls